config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' 
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users/:id/products' => 'products#index', :as => :user_products_path
  get 'users/:id/manufacturers' => 'manufacturers#index', :as => :user_manufacturer_path
  get '/search' => 'search#search', :as => :search_page

  get '/auth/facebook/callback' => 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resource :products
  resource :reviews
  resource :users
  resources :manufacturers

  resources :manufacturers, only: [:show, :search, :new, :create, :update, :destroy] do
    resources :products, only: [:new, :create]
  end

  resources :users do
    resources :products
  end

  resources :users do
    resources :manufacturer
  end

  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  has_and_belongs_to_many :users
  has_many :reviews
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]

    def correct_user
        @manufacturer = Manufacturer.find_by(id: params[:id])
        return unless current_user
        flash[:alert] = "You are not allowed to access this part of the site"
        redirect_to root_path
    end

    def index
        product_helper
        @review = Review.find_by(params[:id])
        @reviews = Review.all
        @products = Product.all
    end

    def show
        product_helper
        @product = Product.all
    end

    def new
        @product = Product.new 
    end 
    
    def create
        @product = Product.create(product_params)
        if @product.save
            @product.update(user_ids: current_user.id)
            # redirect_to products_path(@product)
            redirect_to root_path
        else
            render :new
        end
    end 

    def edit
        product_helper
    end 

    def update
        product_helper
        @product.update(product_params)
        if @product.save
            redirect_to products_path(@product)
        else 
            render :edit 
        end 
    end

    def destroy
        product_helper
        @product.destroy
        redirect_to products_path
    end

    private 

    def product_params
        params.require(:product).permit(:name, :price, :stock, :description, :manufacturer_id, manufacturer_attributes: [:name])
    end 

    def product_helper
        @product = Product.find_by(params[:id])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_with(model: @product, local: true) do |f| %>

<%= f.label :name %>:
<%= f.text_field :name %><br><br>

<%= f.label :price %>
$<%= f.number_field :price, min: 1.00, max: 9999.99%><br><br>

<%= f.label :stock %>:
<%= f.number_field :stock, min: 1.00 %><br><br>

<%= f.label :manufacturer_id %>
<%= f.collection_select :manufacturer_id, Manufacturer.all.sort_by{|m| m.name}, :id, :name, prompt: true  %><br><br>

<%= f.label :description %>:<br><br>
<%= f.text_area :description, :cols => 50, :rows => 7 %><br><br>

<%= f.submit "Update Product" %><br><br>

<%= link_to 'delete', products_path, :method => :delete, data: {:confirm => "Are you sure?" } , :title => "Delete #{@product.name}" %>

<% end %>

app/views/products/index.html.erb
<h1>Products Index</h1>

<% @products.each do |product| %>

<li>Name: <%= @product.name %></li><br>

<li>Price: <%= @product.price %></li><br>

<li>Stock: <%= @product.stock %></li><br>

<li>Description: <%= @product.description %></li><br>

<li>Manufacturer: <%= @product.manufacturer_id %></li><br>

<% end %>

<h1>Product Review</h1>

<% @reviews.each do |review| %>

<li>Rating: <%= @review.rating %>/5.0</li><br>

<li>Comment: <%= @review.comment %></li><br>

<li><%= "Reviewed by #{current_user.email}" %></li><br>

<h4><%= link_to 'Delete Review', reviews_path, :method => :delete, data: {:confirm => "Are you sure?" } , :title => "Delete #{@review}" %></h4><br>

<h1>To show all products and reviews<h1>
    <h4><%= link_to "Show all Products", products_path(@product) %></h4>

    <% end %>

app/views/products/new.html.erb
<h3>Create New Product</h3>

<%= form_with(model: @product, local: true) do |f| %>

<%= f.label :name, "Name:" %>
<%= f.text_field :name %><br><br>

<%= f.label :price, "Price" %>
<%= f.number_field :price, {min: 1.00, max: 100000.00} %><br><br>

<%= f.label :stock, "Stock:" %>
<%= f.number_field :stock, {min: 1, max: 10000} %><br><br>

<%= f.label :manufacturer_id, "Manufacturer:" %>
<%= f.collection_select :manufacturer_id, Manufacturer.all.sort_by{|m| m.name}, :id, :name, prompt: true  %><br><br>

<%= f.label :description, "Description:" %>
<%= f.text_area :description, :cols => 50, :rows => 7 %><br><br>

<%= f.submit "Create New Product" %><br><br>

<% end %>

app/views/products/show.html.erb
<h1>Create New Product</h1>

<h4><%= link_to "Create a new product", new_product_path %></h4>

<h1>All Products</h1>

<% @product.each do |p| %>
<h4>
  <%= link_to p.name, user_products_path(p) %>
  |<%= link_to 'Edit', edit_products_path %>
  |<%= link_to 'Remove', products_path(@product), :confirm => 'Are you sure?', :method => :delete %>|
</h4>

<% end %>