config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' 
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users/:id/products' => 'products#index', :as => :user_products_path
  get 'users/:id/manufacturers' => 'manufacturers#index', :as => :user_manufacturer_path
  get '/search' => 'search#search', :as => :search_page

  get '/auth/facebook/callback' => 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resource :products
  resource :reviews
  resource :users
  resources :manufacturers

  resources :manufacturers, only: [:show, :search, :new, :create, :update, :destroy] do
    resources :products, only: [:new, :create]
  end

  resources :users do
    resources :products
  end

  resources :users do
    resources :manufacturer
  end

  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
  has_many :reviews, through: :products 
  has_many :categories, through: :products
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]

    def correct_user
        @manufacturer = Manufacturer.find_by(id: params[:id])
        return unless current_user
        flash[:alert] = "You are not allowed to access this part of the site"
        redirect_to root_path
    end

    def index
        manufacturer_helper
        @manufacturers = Manufacturer.all
    end
      
    def new
        @manufacturer = Manufacturer.new
    end

    def create
        @manufacturer = Manufacturer.create(manufacturer_params)
        if @manufacturer.save
            @manufacturer.id = current_user.id
            # redirect_to manufacturers_path(@manufacturer)
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
        manufacturer_helper
    end 

    def update
        manufacturer_helper
        @manufacturer.update(manufacturer_params)
        if @manufacturer.save
            redirect_to manufacturers_path(@manufacturer)
        else 
            render :edit 
        end 
    end

    def destroy
        manufacturer_helper
        @manufacturer.destroy
        redirect_to manufacturers_path
    end

    private 

    def manufacturer_params
        params.require(:manufacturer).permit(:name, :bio, :established)
    end

    def manufacturer_helper
        @manufacturer = Manufacturer.find_by(params[:id])
    end

end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/edit.html.erb
<h1>Update or Delete a Manufacturer</h1>

<%= form_with(model: @manufacturer, local: true) do |f| %>

<%= f.label :name %>:
<%= f.text_field :name %><br><br>

<%= f.label :established %>:
<%= f.number_field :established, step: 2020 %><br><br>

<%= f.label :bio %>:<br><br>
<%= f.text_area :bio, :cols => 50, :rows => 7 %><br><br>

<%= f.submit "Update Manufacturer" %><br><br>

<%= link_to 'delete', manufacturers_path, :method => :delete, data: {:confirm => "Are you sure?" } , :title => "Delete #{@manufacturer.name}" %>

<% end %>

app/views/manufacturers/index.html.erb
<h1>Manufacturers Index</h1>

<% @manufacturers.each do |manufacturer| %>

<li>Name: <%= @manufacturer.name %></li><br><br>

<li>Established: <%= @manufacturer.established %></li><br><br>

<li>Bio: <%= @manufacturer.bio %></li><br><br>

<h4>
  <%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %><br>
  <%= link_to 'Delete', manufacturers_path(@manufacturer), :method => :delete, data: {:confirm => "Are you sure?" } , :title => "Delete #{@manufacturer.name}" %><br>
</h4>

<h1>Create New Manufacturer<h1>
    <h4>
      <%= link_to "Create a new manufacturer", new_manufacturer_path %>
    </h4>

    <% end %>

app/views/manufacturers/new.html.erb
<h1>Create New Manufacturer</h1>

<%= form_with(model: @manufacturer, local: true) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %><br><br>

<%= f.label :established %>
<%= f.number_field :established, {min: 1800, max: 2020} %><br><br>

<%= f.label :bio %>
<%= f.text_area :bio, :cols => 50, :rows => 7 %><br><br>

<%= f.submit "Create Manufacturer" %><br><br>

<% end %>