config/routes.rb
Rails.application.routes.draw do
  
  root to: 'main#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' 
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users/:id/products' => 'products#index', :as => :user_products_path
  get 'users/:id/manufacturers' => 'manufacturers#index', :as => :user_manufacturer_path
  get '/search' => 'search#search', :as => :search_page

  get '/auth/facebook/callback' => 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resource :products
  resource :reviews
  resource :users
  resources :manufacturers

  resources :manufacturers, only: [:show, :search, :new, :create, :update, :destroy] do
    resources :products, only: [:new, :create]
  end

  resources :users do
    resources :products
  end

  resources :users do
    resources :manufacturer
  end

  resources :products, only: [:new, :create, :show, :edit, :update] do 
    resources :reviews, only: [:new, :create, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
  has_many :reviews, through: :products 
  has_many :categories, through: :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  has_and_belongs_to_many :users
  has_many :reviews
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :manufacturers, through: :products
  validates :rating, presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :comment, presence: true
 
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :products
  has_many :reviews
  has_many :manufacturers, through: :products 
    
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true 
  validates :username, presence: true, uniqueness: true

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]

    def correct_user
        @manufacturer = Manufacturer.find_by(id: params[:id])
        return unless current_user
        flash[:alert] = "You are not allowed to access this part of the site"
        redirect_to root_path
    end

    def index
        product_helper
        @review = Review.find_by(params[:id])
        @reviews = Review.all
        @products = Product.all
    end

    def show
        product_helper
        @product = Product.all
    end

    def new
        @product = Product.new 
    end 
    
    def create
        @product = Product.create(product_params)
        if @product.save
            @product.update(user_ids: current_user.id)
            # redirect_to products_path(@product)
            redirect_to root_path
        else
            render :new
        end
    end 

    def edit
        product_helper
    end 

    def update
        product_helper
        @product.update(product_params)
        if @product.save
            redirect_to products_path(@product)
        else 
            render :edit 
        end 
    end

    def destroy
        product_helper
        @product.destroy
        redirect_to products_path
    end

    private 

    def product_params
        params.require(:product).permit(:name, :price, :stock, :description, :manufacturer_id, manufacturer_attributes: [:name])
    end 

    def product_helper
        @product = Product.find_by(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]

    def correct_user
        @manufacturer = Manufacturer.find_by(id: params[:id])
        return unless current_user
        flash[:alert] = "You are not allowed to access this part of the site"
        redirect_to root_path
    end
    
    def new
        review_helper
        @product = Product.find_by(params[:id])
        @products = Product.all
        @review = Review.new
    end 

    def create 
        review_helper
        @review = Review.create(review_params)
        if @review.save 
            redirect_to product_path(@review.product_id)
        else 
            render :new
        end 
    end 

    def show
    end 

    def destroy
        @review = Review.find_by(params[:id])
        @review.destroy
        redirect_to products_path(@product)
    end 

    private

    def review_params
        params.require(:review).permit(:product_id, :rating, :comment, :user_id )
    end

    def review_helper
        params[:product_id] && @product = Product.find_by_id(params[:product_id])
    end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search  
    if params[:search].blank?
      redirect_to root_path, notice: "Empty field!"
    else
      @parameter = params[:search].downcase
      @product = Product.find_by(params[:id])
      @products = Product.all 
    end  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_log_in, only: [:show]

  def new
    @user = User.new
  end 

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end 

  def show
    user_helper
  end 

  def edit
    user_helper
  end

  def update
      user_helper
      @user.update(user_params)
      if @user.save
        redirect_to users_path(@user)
      else 
        render :edit 
      end 
    end
      
  private

    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end
    
    def user_helper
      @user = User.find_by(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user?(user)
    user == current_user
  end

  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
<div id="error-explanation">
  <div id="error_block">
    <p><%= pluralize(object.errors.count, 'error') %><br>
      <b>Your request could not be completed:</b></p><br>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>

  <head>
    <div class="center hero-unit">
      <h1>AClickAway</h1>
      <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Product Search", class: "form-control" %>
        <div class="input-group-btn">
          <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
        </div>
      </div>
      <% end %>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </div>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav pull-right">
              <% if current_user %>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to  "Manufacturer Info", manufacturers_path %></li>
              <li><%= link_to "Show User Products", products_path %></li>
              <li><%= link_to  "Review a Product", new_reviews_path %></li>
              <li><%= link_to  "Edit User Info", edit_users_path(current_user) %></li>
              <li><%= link_to 'Log Out', logout_path, method: "delete" %></li>
              <% else %>
              <div> <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', signup_path %> </div>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>

  <footer class="footer">
    <% if current_user %>
    <p><small><%= "Signed in as #{current_user.email}"  %> &copy; 2020 <strong>A Click Away</strong></small></p>
    <% end %>
  </footer>

  </html>